### ISSUE TITLE
Usage doc

### ISSUE THREAD

**Issue by ahmgeek** [bys-control/activeadmin-ajax_forms#6]
usage please, usage docs ASAP

**Comment by cpfarher** [comment]
Do you check the [Wiki](https://github.com/bys-control/activeadmin-ajax_forms/wiki)?

**Comment by ahmgeek** [comment]
yeah, it's not in English.

**Comment by gbisheimer** [comment]
I opened issue #7 to reference this.

**Comment by ahmgeek** [comment]
I wish I could help translating, but I only know Arabic And English...
thanks.

**Comment by ahmgeek** [comment]
BTW, I saw [comments](https://github.com/bys-control/activeadmin-ajax_forms/blob/master/lib/ajax_forms/dsl.rb#L43) on code, that needs to be in English it its stayed there.
